### ISSUE TITLE
Is any sample app source that used this?

### ISSUE THREAD

**Issue by isaeid63** [rubenlagus/Deepthought#11]
I want to use this project to learn how we can use telegram apis. 
I found TLsharp project in c# but they have many compile problems.

**Comment by rubenlagus** [comment]
The api was moved to https://github.com/rubenlagus/telegramapi. I'll update this project, eventually, with an example. Of that api usage.

**Comment by rubenlagus** [comment]
@isaeid63, the api is updated and now it is a sample usage of the api.
