### ISSUE TITLE
Get messages of a channel and remove them by super admin

### ISSUE THREAD

**Issue by azimot** [rubenlagus/Deepthought#6]
when i am a channel creator (super admin) i could to remove any message of me or other the channel admins.
so i need to get messageId(s) and after to make a list of them then i could to remove all
 according to telegram api document that happen with "messages.deleteMessages"

https://core.telegram.org/method/messages.deleteMessages

but i can not to find fixed handler for that and how to can i to remove some messages 
any code example or even short detail for that ?

**Comment by azimot** [comment]
i see i could to send method by json type too and "messages.deleteMessages" method is presented ::
https://core.telegram.org/schema/json
`

           {
            "id": "351460618",
            "method": "messages.deleteMessages",
            "params": [{
                    "name": "id",
                    "type": "Vector<int>"
                }],
            "type": "Vector<int>"
           }


`
is possible to do this task by sending JSON data to telegram server ?
( i could to setup a http server for that )
i really need to have this feature by API implementation  or by any other way because minimum removable message is 3000 messages every day and it's not possible to selected by clicking one by one in telegram client

**Comment by rubenlagus** [comment]
No, Telegram servers doesn't support plain requests, you need to use MTPROTO implementation. 

Btw, the api was moved to https://github.com/rubenlagus/TelegramApi
