### ISSUE TITLE
How to send message using phone number not user_id?

### ISSUE THREAD

**Issue by ibgithub** [rubenlagus/Deepthought#9]
How to send message using phone number not user_id? is it we need to get user_id first and then send message?
And to get user_id is using TLRequestContactsImportContacts object? please help me or if there is some references, thank you.

**Comment by rubenlagus** [comment]
You need to import contacts first and you will receive the id and accessHash. 

P.D: Api was moved to https://github.com/rubenlagus/TelegramApi
